# Generated by Django 4.2.6 on 2023-10-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchresult", old_name="published_at", new_name="publishedAt",
        ),
    ]
