# Generated by Django 4.2.6 on 2023-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0002_rename_published_at_searchresult_publishedat"),
    ]

    operations = [
        migrations.RemoveField(model_name="searchquery", name="created_at",),
        migrations.AddField(
            model_name="searchquery",
            name="last_search_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
